# Generated by Django 3.1 on 2021-02-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicSession',
        ),
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='school_name',
            field=models.CharField(default='XYZ Public School', max_length=200),
        ),
    ]
