# Generated by Django 3.1 on 2021-02-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210211_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='school_name',
        ),
    ]
