# Generated by Django 3.1 on 2021-02-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210207_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='takes_web_lecture',
            field=models.BooleanField(default=False),
        ),
    ]
