# Generated by Django 3.1 on 2021-02-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20210207_1124'),
        ('staff', '0002_staff_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subjects',
        ),
        migrations.AddField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(to='subject.Subject'),
        ),
    ]
