# Generated by Django 3.1 on 2021-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=5000)),
                ('web_lecture', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('shape', models.CharField(choices=[('oval', 'Oval'), ('rectangular', 'Rectangular'), ('canopy', 'Canopy'), ('elevated', 'Elevated')], default='male', max_length=20)),
            ],
        ),
    ]
