# Generated by Django 3.1 on 2021-02-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210207_1124'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chapters', models.IntegerField(default=1)),
                ('total_duration', models.DurationField()),
                ('per_class_duration', models.DurationField()),
                ('classroom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
