# Generated by Django 3.1 on 2021-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='UNASSIGNED', max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=30),
        ),
    ]
