# Generated by Django 3.1 on 2021-02-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20210208_1921'),
        ('staff', '0004_staff_takes_web_lecture'),
        ('classroom', '0002_auto_20210207_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(related_name='classroom_subjects', to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='classroom_teachers', to='staff.Staff'),
        ),
    ]
