# Generated by Django 3.1 on 2021-02-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20210208_1921'),
        ('staff', '0004_staff_takes_web_lecture'),
        ('classroom', '0004_auto_20210211_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(default=[], related_name='classroom_subjects', to='subject.Subject'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(default=[], related_name='classroom_teachers', to='staff.Staff'),
        ),
    ]
