# Generated by Django 3.1 on 2021-02-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20210208_1921'),
        ('student', '0002_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default=[], to='subject.Subject'),
        ),
    ]
