# Generated by Django 3.1 on 2021-02-08 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0004_staff_takes_web_lecture'),
        ('student', '0002_student_subjects'),
        ('classroom', '0003_auto_20210208_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_classroom', to='classroom.classroom')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='student.student')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_teacher', to='staff.staff')),
            ],
        ),
    ]
